import db from './client.js';

const sql = `
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, phone TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS businesses (id INTEGER PRIMARY KEY AUTOINCREMENT, owner_user_id INTEGER NOT NULL, name TEXT NOT NULL, gstin TEXT, pan TEXT, phone TEXT, email TEXT, address_json TEXT, logo_url TEXT, bank_details_json TEXT, invoice_settings_json TEXT, invoice_prefix TEXT DEFAULT 'INV-', invoice_start INTEGER DEFAULT 1, invoice_theme TEXT DEFAULT 'classic', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS business_users (id INTEGER PRIMARY KEY AUTOINCREMENT, business_id INTEGER NOT NULL, user_id INTEGER NOT NULL, role TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS parties (id INTEGER PRIMARY KEY AUTOINCREMENT, business_id INTEGER NOT NULL, type TEXT NOT NULL, name TEXT NOT NULL, phone TEXT, email TEXT, gstin TEXT, pan TEXT, city TEXT, billing_address_json TEXT, shipping_address_json TEXT, credit_limit REAL DEFAULT 0, credit_period_days INTEGER DEFAULT 0, opening_balance REAL DEFAULT 0, opening_balance_type TEXT DEFAULT 'dr', notes TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS item_categories (id INTEGER PRIMARY KEY AUTOINCREMENT, business_id INTEGER NOT NULL, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY AUTOINCREMENT, business_id INTEGER NOT NULL, name TEXT NOT NULL, type TEXT DEFAULT 'product', category_id INTEGER, unit TEXT, hsn_sac TEXT, purchase_price REAL DEFAULT 0, mrp REAL DEFAULT 0, selling_price REAL DEFAULT 0, tax_rate REAL DEFAULT 0, current_stock REAL DEFAULT 0, min_stock_alert REAL DEFAULT 0, description TEXT, image_url TEXT, sku TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS stock_movements (id INTEGER PRIMARY KEY AUTOINCREMENT, business_id INTEGER NOT NULL, item_id INTEGER NOT NULL, movement_type TEXT NOT NULL, qty_change REAL NOT NULL, balance_after REAL NOT NULL, reference_id INTEGER, reference_type TEXT, notes TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS invoices (id INTEGER PRIMARY KEY AUTOINCREMENT, business_id INTEGER NOT NULL, invoice_number TEXT NOT NULL, type TEXT DEFAULT 'invoice', source_invoice_id INTEGER, party_id INTEGER NOT NULL, invoice_date TEXT NOT NULL, due_date TEXT, status TEXT DEFAULT 'draft', subtotal REAL DEFAULT 0, discount_total REAL DEFAULT 0, tax_total REAL DEFAULT 0, round_off REAL DEFAULT 0, grand_total REAL DEFAULT 0, amount_paid REAL DEFAULT 0, payment_mode TEXT, notes TEXT, terms TEXT, is_same_state INTEGER DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS invoice_items (id INTEGER PRIMARY KEY AUTOINCREMENT, invoice_id INTEGER NOT NULL, item_id INTEGER, item_name TEXT NOT NULL, hsn_sac TEXT, qty REAL NOT NULL, unit TEXT, rate REAL NOT NULL, discount_pct REAL DEFAULT 0, tax_rate REAL DEFAULT 0, tax_amount REAL DEFAULT 0, amount REAL DEFAULT 0);
CREATE TABLE IF NOT EXISTS payments_received (id INTEGER PRIMARY KEY AUTOINCREMENT, business_id INTEGER NOT NULL, invoice_id INTEGER NOT NULL, party_id INTEGER NOT NULL, amount REAL NOT NULL, payment_date TEXT NOT NULL, payment_mode TEXT, notes TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS purchase_bills (id INTEGER PRIMARY KEY AUTOINCREMENT, business_id INTEGER NOT NULL, bill_number TEXT NOT NULL, party_id INTEGER NOT NULL, bill_date TEXT NOT NULL, due_date TEXT, status TEXT DEFAULT 'unpaid', subtotal REAL DEFAULT 0, tax_total REAL DEFAULT 0, grand_total REAL DEFAULT 0, amount_paid REAL DEFAULT 0, notes TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS purchase_bill_items (id INTEGER PRIMARY KEY AUTOINCREMENT, purchase_bill_id INTEGER NOT NULL, item_id INTEGER, item_name TEXT NOT NULL, qty REAL NOT NULL, unit TEXT, rate REAL NOT NULL, tax_rate REAL DEFAULT 0, tax_amount REAL DEFAULT 0, amount REAL DEFAULT 0);
CREATE TABLE IF NOT EXISTS expenses (id INTEGER PRIMARY KEY AUTOINCREMENT, business_id INTEGER NOT NULL, category TEXT NOT NULL, amount REAL NOT NULL, expense_date TEXT NOT NULL, payment_mode TEXT, notes TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS custom_fields (id INTEGER PRIMARY KEY AUTOINCREMENT, business_id INTEGER NOT NULL, label TEXT, field_type TEXT, applies_to TEXT, is_required INTEGER DEFAULT 0);
`;

db.exec(sql);
console.log('Migrated');
